version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      redis-stack:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis-stack:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  identity-service:
    build: ./identity-service
    env_file: ./identity-service/.env
    depends_on:
      redis-stack:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis-stack:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    depends_on:
      redis-stack:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis-stack:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  media-service:
    build: ./media-service
    env_file: ./media-service/.env
    depends_on:
      redis-stack:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis-stack:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  search-service:
    build: ./search-service
    env_file: ./search-service/.env
    depends_on:
      redis-stack:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis-stack:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: Password
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: Admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password
    depends_on:
      mongo:
        condition: service_healthy

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"   # Redis server
      - "8001:8001"   # Redis Stack UI
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
